// Required imports


// Components, styling, assets
import { Raleway } from "next/font/google";
import "./globals.css";

const raleway = Raleway({ 
  subsets:["latin"],
  display:'swap',
  weights:['400','500','600']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return(
    <html lang="en">
      <body className={raleway.className}>
        {children}
      </body>
    </html>
  );

}
